### ISSUE TITLE
Error while deploying openApi files (Migration v1 to v2.)

### ISSUE THREAD

**Issue by m-murad** [cloudendpoints/endpoints-python#75] opened 2017-08-07 17:11 UTC
Following is the structure of my project
![screen shot 2017-08-07 at 8 02 46 pm](https://user-images.githubusercontent.com/17262180/29031327-7b872c0c-7bab-11e7-9951-18926ff6f8e0.png)

I have written two APIs (`OrdersApi` and `UsersApi`) in two separate files (`orders.py` and `users.py`). For both `version='v1'`

I generated the Open API configuration files for both APIs by running the following commands

`python lib/endpoints/endpointscfg.py get_openapi_spec apis.OrdersApi apis.UsersApi --hostname office-needs.appspot.com`

This gave me two files `ordersv1openapi.json`  and `usersv1openapi.json`.

But when I run 
`gcloud service-management deploy ordersv1openapi.json usersv1openapi.json `
I get the following error

```
ERROR: (gcloud.service-management.deploy) INVALID_ARGUMENT: kind: ERROR
message: "Multiple OpenAPI files cannot have the same \'info.version\' value. Files and Versions found: {ordersv1openapi.json:v1, usersv1openapi.json:v1}"
```

**Comment by inklesspen** [comment] 2017-09-01 21:58
Dupe of #47

**Closed by inklesspen** 2017-09-01 21:58 UTC

**Comment by inklesspen** [comment] 2017-09-29 17:55
This has been added to the endpoints [Known Issues](https://cloud.google.com/endpoints/docs/known-issues) page.
